### ISSUE TITLE
Maybe not an issue

### ISSUE THREAD

**Issue by NathanSalapat** [LandonAConway/fire_realism#1]
Looking at the code it looks like you're using an abm on group:cool_ash for regenerating the biome data, is there any reason that each type of dirt needs a hot and cool ash version. Doesn't the biome update swap that out, or is that needed to change the dirt nodes back to what they were originally. If they are needed you may want to remove them from creative inventory. :)

**Comment by LandonAConway** [comment]
Yes. I did this becuase they are used to return the nodes back to normal. Originally, i would have created a single ash node and hot ash node and use meta to know the original node. However, this was not working properly so I decided to implement this method.

I will remove them from the creative inventory today. Be prepared to install a new update within the next couple hours today.

**Comment by LandonAConway** [comment]
Project has been updated.
